import os
from os import path as osp

__all__ = ['find_best_ckpt']


def find_best_ckpt(log_dir):
    """
    Find the best checkpoint for a given log directory.
    :param log_dir: the directory generated by pytorch-lightning, contains:
     1. a "checkpoints" directory
     2. event files
     3. hyperparameter file named "hparams.yaml"
    :return: the best checkpoint path in the "checkpoints" director
    """

    if 'checkpoints' not in os.listdir(log_dir):
        return None
    ckpts = filter(lambda x: x.endswith('ckpt'), os.listdir(osp.join(log_dir, 'checkpoints')))
    ckpt_path = None
    for ckpt in ckpts:
        p = osp.join(log_dir, 'checkpoints', ckpt)
        if ckpt == 'last.ckpt' and ckpt_path is None:
            ckpt_path = p
        else:
            ckpt_path = p

    return ckpt_path


if __name__ == '__main__':
    find_best_ckpt('')
